"""Next-step feature-forecasting head over backbone token sequences.

Given a short temporal stack of backbone token maps describing the same scene
at successive revisits, this head predicts the next frame of features. In the
dark-vessel setting the motivating use is short-horizon forecasting of a
per-patch feature field (e.g. anticipating the next-revisit embedding so an
anomaly score can be computed before the next acquisition lands).

HONESTY / synthetic data
------------------------
The data here is SYNTHETIC, not a real Earth-observation time series. Each
sequence is generated by starting from a random token map ``(N, D)`` and
evolving it for ``T + 1`` steps with a FIXED, seeded linear operator acting in
the ``D``-dimensional feature space (a drift / rotation matrix) plus small
additive noise. The deterministic operator is the learnable signal: the head
must recover the per-step dynamics to forecast frame ``T + 1``. The honest
baseline is *persistence* (predict the last observed frame); ``train_eval``
reports it alongside the head so any improvement is measured against it. These
metrics show the head can learn linear feature dynamics on structured tokens;
they are not an EO benchmark.
"""
from __future__ import annotations

import math

import torch
import torch.nn as nn
import torch.nn.functional as F

from darkvessel.heads.common import map_to_tokens, tokens_to_map


class ForecastHead(nn.Module):
    """Predict the next token frame from a stack of ``T`` observed frames.

    The head pools the observed time axis with a learned per-step weighting,
    applies a small per-token MLP that models the feature-space transition, and
    adds a learned residual to the most recent frame. The residual formulation
    means the head only has to learn the *change* from persistence, which is
    exactly the planted linear-dynamics signal.
    """

    def __init__(self, embed_dim: int = 64, grid: int = 8, n_steps: int = 4, hidden: int = 128) -> None:
        super().__init__()
        self.embed_dim = embed_dim
        self.grid = grid
        self.n_steps = n_steps
        # learned weighting over the observed frames (softmax-normalised at use)
        self.time_weight = nn.Parameter(torch.zeros(n_steps))
        # per-token transition MLP operating in D-space; predicts the delta to add
        # to the last frame, so it learns the operator minus identity.
        self.transition = nn.Sequential(
            nn.Linear(2 * embed_dim, hidden),
            nn.GELU(),
            nn.Linear(hidden, hidden),
            nn.GELU(),
            nn.Linear(hidden, embed_dim),
        )

    def forward(self, seq: torch.Tensor) -> torch.Tensor:
        """Forecast the next token frame.

        Parameters
        ----------
        seq: ``(B, T, N, D)`` stack of ``T`` observed token frames.

        Returns
        -------
        ``(B, N, D)`` predicted next frame (frame ``T + 1``).
        """
        b, t, n, d = seq.shape
        last = seq[:, -1]                                   # (B, N, D) persistence anchor
        # learned temporal context: weighted average over the observed frames
        w = F.softmax(self.time_weight[:t], dim=0)          # (T,)
        context = torch.einsum("t,btnd->bnd", w, seq)       # (B, N, D)
        feats = torch.cat([last, context], dim=-1)          # (B, N, 2D)
        delta = self.transition(feats)                      # (B, N, D)
        return last + delta


def make_synthetic(
    n: int,
    embed_dim: int = 64,
    grid: int = 8,
    seed: int = 0,
    steps: int = 4,
    noise: float = 0.02,
    op_scale: float = 0.15,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Synthetic temporal token sequences with deterministic linear dynamics.

    Structure (all generated from a seeded ``torch.Generator``):

    * A single FIXED transition operator ``A = I + op_scale * R`` is drawn once,
      where ``R`` is a random ``(D, D)`` matrix scaled by ``1/sqrt(D)``. ``A`` acts
      in feature space and is shared across every sequence and patch (the dynamics
      to be learned). The ``I +`` keeps the map near-identity so the last frame is
      a strong but beatable persistence baseline.
    * For each of ``n`` sequences, a random initial token map ``x0`` of shape
      ``(N, D)`` (``N = grid * grid``) is evolved for ``steps + 1`` frames:
      ``x_{k+1} = x_k @ A^T + noise * eps_k``.
    * ``inputs`` are the first ``steps`` frames ``(n, steps, N, D)``; ``target`` is
      frame ``steps + 1`` ``(n, N, D)``.

    The additive noise makes the forecast non-trivial; the operator ``A`` is the
    real, learnable signal that lets the head beat persistence.
    """
    g = torch.Generator().manual_seed(seed)
    N = grid * grid
    D = embed_dim
    # The transition operator defines the TASK; it must be identical across the
    # train and eval splits (different sample seeds), so draw it from a fixed
    # task generator rather than the per-split `seed`.
    sig_gen = torch.Generator().manual_seed(20240601)
    R = torch.randn(D, D, generator=sig_gen) / math.sqrt(D)
    A = torch.eye(D) + op_scale * R                          # (D, D)

    x = torch.randn(n, N, D, generator=g)                    # initial maps (B, N, D)
    frames = [x]
    for _ in range(steps):
        nxt = frames[-1] @ A.t() + noise * torch.randn(n, N, D, generator=g)
        frames.append(nxt)
    # one more step for the target frame (steps + 1 total transitions from x0)
    target = frames[-1] @ A.t() + noise * torch.randn(n, N, D, generator=g)

    inputs = torch.stack(frames[:steps], dim=1)              # (n, steps, N, D)
    return inputs, target


def train_eval(
    steps: int = 220,
    seed: int = 0,
    n_train: int = 256,
    n_eval: int = 256,
    embed_dim: int = 64,
    grid: int = 8,
    t_obs: int = 4,
    lr: float = 3e-3,
    **kw,
) -> dict:
    """Train ``ForecastHead`` on synthetic dynamics; eval on a fresh set.

    Trains with MSE (Adam) and evaluates on a freshly seeded synthetic set.
    Reports the head's MSE plus the HONEST persistence baseline (predicting the
    last observed frame). Returns at least ``mse``, ``mse_persistence``,
    ``mse_start`` and ``mse_end``.
    """
    torch.manual_seed(seed)

    x_tr, y_tr = make_synthetic(n_train, embed_dim, grid, seed=seed, steps=t_obs)
    x_ev, y_ev = make_synthetic(n_eval, embed_dim, grid, seed=seed + 1, steps=t_obs)

    head = ForecastHead(embed_dim=embed_dim, grid=grid, n_steps=t_obs)
    opt = torch.optim.Adam(head.parameters(), lr=lr)

    @torch.no_grad()
    def eval_mse() -> float:
        head.eval()
        pred = head(x_ev)
        m = F.mse_loss(pred, y_ev).item()
        head.train()
        return m

    # honest persistence baseline on the eval set: predict the last observed frame
    mse_persistence = F.mse_loss(x_ev[:, -1], y_ev).item()

    mse_start = eval_mse()
    for _ in range(steps):
        opt.zero_grad()
        pred = head(x_tr)
        loss = F.mse_loss(pred, y_tr)
        loss.backward()
        opt.step()
    mse_end = eval_mse()

    return {
        "mse": mse_end,
        "mse_persistence": mse_persistence,
        "mse_start": mse_start,
        "mse_end": mse_end,
    }


__all__ = ["ForecastHead", "make_synthetic", "train_eval"]
